"""Rename error

Revision ID: 043bb2a824b8
Revises: 37466ade5c40
Create Date: 2025-09-10 10:05:24.748757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '043bb2a824b8'
down_revision: Union[str, Sequence[str], None] = '37466ade5c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_errors_created_at'), 'errors', ['created_at'], unique=False)
    op.create_index(op.f('ix_errors_text'), 'errors', ['text'], unique=False)
    op.drop_index(op.f('ix_Error_created_at'), table_name='Error')
    op.drop_index(op.f('ix_Error_text'), table_name='Error')
    op.drop_table('Error')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Error',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Error_pkey'))
    )
    op.create_index(op.f('ix_Error_text'), 'Error', ['text'], unique=False)
    op.create_index(op.f('ix_Error_created_at'), 'Error', ['created_at'], unique=False)
    op.drop_index(op.f('ix_errors_text'), table_name='errors')
    op.drop_index(op.f('ix_errors_created_at'), table_name='errors')
    op.drop_table('errors')
    # ### end Alembic commands ###
