"""Add error tracking table

Revision ID: 37466ade5c40
Revises: 570b3bc0d904
Create Date: 2025-09-10 10:01:36.272159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '37466ade5c40'
down_revision: Union[str, Sequence[str], None] = '570b3bc0d904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Error_created_at'), 'Error', ['created_at'], unique=False)
    op.create_index(op.f('ix_Error_text'), 'Error', ['text'], unique=False)
    op.drop_constraint(op.f('employees_email_key'), 'employees', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('employees_email_key'), 'employees', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_Error_text'), table_name='Error')
    op.drop_index(op.f('ix_Error_created_at'), table_name='Error')
    op.drop_table('Error')
    # ### end Alembic commands ###
