"""Fix foreign key

Revision ID: 570b3bc0d904
Revises: 7ea7a3a2c666
Create Date: 2025-09-10 00:45:14.655238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570b3bc0d904'
down_revision: Union[str, Sequence[str], None] = '7ea7a3a2c666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'employee_roles', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_roles', type_='foreignkey')
    # ### end Alembic commands ###
